### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by rtfpessoa** [fnxpt/codacy-swiftlint#5]
@fnxpt do you need anything from my side to fix the remaining issues?

**Comment by fnxpt** [comment]
@rtfpessoa, the remaining issues are related with docker hub credentials. should I fix this issues in order to get a 100% working build, or should I wait for you guys to implement it on your side (repo).

**Comment by fnxpt** [comment]
@rtfpessoa, the build is now failing because its trying to push the docker image to codacy/codacy-swiftlint, should I change codacy to my docker user.

**Comment by rtfpessoa** [comment]
@fnxpt sorry, must have seen the wrong build. Than it should be done. I will now pull this to codacy repo and try to release.

**Comment by rtfpessoa** [comment]
Apparently it is failing randomly. Any ideas? https://circleci.com/gh/codacy/codacy-swiftlint/11

Everything is running in separate dockers not sure how the tool can fail from time to time.

**Comment by fnxpt** [comment]
@rtfpessoa , sorry for the delay... I have no idea what's happening but I will try to see what's happening.

**Comment by rtfpessoa** [comment]
Maybe we can open an issue with the guys from Swiftlint

**Comment by fnxpt** [comment]
This issue is fixed on my latest PR. Closing this for now
